name: Build

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: globalid/github-actions/java-setup@main
      - name: Build with Maven
        run: mvn -B verify --file pom.xml

