name: Build
"on":
  push:
    branches:
      - '**'
    tags:
      - v*
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    name: run-tests
    permissions:
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - shell: sh
        run: mvn -B verify -ntp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
